# Generated by Django 3.2 on 2023-05-27 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
